version: '3.8'

services:

  # -- USUARIOS --
  postgresUsers:
    container_name: "postgresUsers"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_DB=usuarios
    volumes:
      - postgresUsers:/var/lib/postgresql/data

  supertechnology-usuarios:
    build: ./usuarios-api
    container_name: "supertechnology-usuarios"
    environment:
      - POSTGRES_CONNECTION=r2dbc:postgresql://postgres:postgres1234@postgresUsers/usuarios
      - JWT_SECRET=Zanahoria_Turbopropulsada9
      - KEY_STORE_PATH=classpath:.cert/server_key.p12
    ports:
      - '6969:6969'
    depends_on:
      - postgresUsers

  # -- PRODUCTOS --
  mariadbProductos:
    container_name: "mariadbProductos"
    image: mariadb:latest
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: "mariadb1234"
      MYSQL_DATABASE: "productos"
      MYSQL_USER: "mariadb"
      MYSQL_PASSWORD: "mariadb1234"
    volumes:
      - db:/var/lib/mariadb/data

  supertechnology-productos:
    build: ./productos-api
    container_name: "supertechnology-productos"
    environment:
      - MARIADB_CONNECTION=r2dbc:mariadb://mariadb:mariadb1234@mariadbProductos/productos
    restart: always
    ports:
      - '6963:6963'
    depends_on:
      - mariadbProductos

  # -- PEDIDOS --


volumes:
  postgresUsers:
    driver: local
  db:
    driver: local